// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSxuCS4wWj9As2hON_0136PsSy_V7SePw',
    appId: '1:529632779142:web:71c4d55bdbe7e52efcea07',
    messagingSenderId: '529632779142',
    projectId: 'fasum1-app',
    authDomain: 'fasum1-app.firebaseapp.com',
    storageBucket: 'fasum1-app.appspot.com',
    measurementId: 'G-0ELWVPN0TY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDcVOKKIbTlBFtDCfWcLMlkgtRjNeksQQ',
    appId: '1:529632779142:android:076f165c876e86cefcea07',
    messagingSenderId: '529632779142',
    projectId: 'fasum1-app',
    storageBucket: 'fasum1-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlh_wrzPRATblHkuDuDTi1D1ciSiNl0rI',
    appId: '1:529632779142:ios:217b6e7523eb0119fcea07',
    messagingSenderId: '529632779142',
    projectId: 'fasum1-app',
    storageBucket: 'fasum1-app.appspot.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlh_wrzPRATblHkuDuDTi1D1ciSiNl0rI',
    appId: '1:529632779142:ios:e9b59ddab3ffd013fcea07',
    messagingSenderId: '529632779142',
    projectId: 'fasum1-app',
    storageBucket: 'fasum1-app.appspot.com',
    iosBundleId: 'com.example.fasum.RunnerTests',
  );
}
